### ISSUE TITLE
`update_coefficients` conflicts with `SciMLBase`

### ISSUE THREAD

**Issue by gaurav-arya** [SciML/SciMLOperators.jl#121]
`SciMLBase` also exports `update_coefficients` and `update_coefficients!`, which conflict with the exported functions here when the packages are used concurrently with `using`. Would it be better to use `SciMLBase`'s function here?

**Comment by vpuri3** [comment]
this package isn't integrated with the last of sciml ecosystem. use it with caution. plan to do that as soon as i get free from other stuff. eventually scimlbase will depend on scimloperators and reexport it.

if you still want to use it, I would recommend importing scimloperators and calling update_coefficients! as scimloperators.update_coefficients!

**Comment by ChrisRackauckas** [comment]
See https://github.com/SciML/SciMLOperators.jl/issues/55. SciMLOperators needs some downstream libraries to adopt it (and likely a few bug fixes) before it's used. This will be the library that defines these functions and SciMLBase's will be replaced with the functions defined here (since the notion of an operator is something that can be used more generally). But as the docs say, this library is not complete and use with caution until it's integrated with all things downstream.

**Comment by vpuri3** [comment]
close
