### ISSUE TITLE
fft wrapper example

### ISSUE THREAD

**Issue by AshtonSBradley** [SciML/SciMLOperators.jl#123]
A couple of observations in testing, in case it is useful.

First, I notice that the first code block in 

https://docs.sciml.ai/SciMLOperators/dev/tutorials/fftw/

runs fine. The second one is different and currently throws an error. 

Second, making the obvious changes to the code that works to allow complex input, the tests pass provided I also make the `x` vector complex: 

```
        n = 256
	l = 2π
	
	dx = l / n
	x  = range(-l/2, l/2, n+1)[1:n] |> Array
	u  = @. sin(5x)cos(7x)  + im*cos(x) |> complex  
	du = @. 5cos(5x)cos(7x) - 7sin(5x)sin(7x)  - im*sin(x) |> complex
	
	k  = fftfreq(n, 2π*n/l) |> Array
	m  = length(k)
	tr = plan_fft(u)

         L = FunctionOperator(
					(du,u,p,t) -> mul!(du, tr, u), u,u,
                                          isinplace=true,
                                         T=ComplexF64,
					op_adjoint = (du,u,p,t) -> ldiv!(du, tr, u),
					op_inverse = (du,u,p,t) -> ldiv!(du, tr, u),
					op_adjoint_inverse = (du,u,p,t) -> ldiv!(du, tr, u),
                    )

	ik = im * DiagonalOperator(k)
	∂x = L \ ik * L
	
	Dx = cache_operator(∂x, complex(x))
	
	@show ≈(Dx * u, du; atol=1e-8)
	@show ≈(mul!(copy(u), Dx, u), du; atol=1e-8)
```
true 

Is this the intended behavior? Could there be unexpected side effects of this complexification of the `x` vector? Just wondering about testing further with e.g. `SplitODEProblem` and `ETDRK4`.

**Comment by vpuri3** [comment]
Hi @AshtonSBradley , thanks for pointing out the error in the docs. I'll fix it. Regarding your second point, the operation `L = cache_operator(L, u_input)` creates copies of `u_input` so that operations like `L * u, mul!(v, L, u, a, b)` are cached and nonallocating. Here, `u_input` should be the similar to (same shape and type) the kind of array that you want to feed to `L`. Since copies of the input array are preallocated, you can only multiply `L` with arrays of the same kind (type and shape).

For your code block, you want to cache the operator with `u` as in
```julia
Dx = cache_operator(∂x, u)
```
as `u (Vector{ComplexF64})` is the kind of array you want to multiply with `Dx`, not `x (Vector{Float64})`.

**Comment by vpuri3** [comment]
to clarify, no sideeffects of complexification. :)
