### ISSUE TITLE
Diagonal operator vs batched diagonal operator

### ISSUE THREAD

**Issue by gaurav-arya** [SciML/SciMLOperators.jl#158]
Is there a reason why both of these exist in the code base? It doesn't seem easy to construct a diagonal operator as the default is a batched diagonal operator.

Also, is the below line dangerous? It looks like it would drop the `update_func`.
https://github.com/SciML/SciMLOperators.jl/blob/31275d4e2b2f3671fb4c2811656dd555c4e1f24a/src/matrix.jl#L116

**Comment by vpuri3** [comment]
that should create a `Diagonal` matrix. Can you create a PR to fix that?

**Comment by vpuri3** [comment]
Yes there are two different use cases.

(1) `DiagonalOperator` can be used for the very common case where `L.A` is a diagonal matrix.
```julia
N, K = 3, 4
d = Diagonal(N)
u = rand(N, K)
A = DiagonalOperator(d) # MatrixOperator
v = A * u
```
will pointwise multiply each column on `u` with `d`.

(2) Consider the following case: you are evolving an ODE with `size(u) = (N,K)`, ie you have `K` trajectories of size `N`. A very common operation you want to perform is pointwise multiplication, i.e. for every trajectory `k`, you want to do `d[:,k] .* u[:,k]`. This is common when you want to form a nonlinear term like `u^2` in a Navier-Stokes or a Burgers solver. That's what `BatchedDiagonalOperator` allows you to do:
```julia
N, K = 3, 4
d = rand(N, K)
u = rand(N, K)
A = DiagonalOperator(d) # BatchedDiagonalOperator
v = A * u
```

If you look at the methods, `DiagonalOperator(d::AbstractArray)` is a convenience function that dispatches to `MatrixOperator` when `d isa AbstractVector`, and `BatchedDiagonalOperator` otherwise. We have tests to make sure the correct type is instantiated (`MatrixOperator`, or `BatchedDiagonalOperator`). Feel free to add more tests if you think there are corner cases. There is no type called `DiagonalOperator` - it is just a convenience.

**Comment by vpuri3** [comment]
I'm sure there are other operations that we'd want to implement in a `Batched` way, ie when you want to apply unique data to each trajectory/batch. I just haven't come across yet.

**Comment by gaurav-arya** [comment]
If `Diagonal` should create a regular diagonal matrix, not a SciMLOperator, then is the following line from tests also wrong?
https://github.com/SciML/SciMLOperators.jl/blob/31275d4e2b2f3671fb4c2811656dd555c4e1f24a/test/total.jl#L92
It seems you were trying to create a lazy diagonal operator here?

**Comment by vpuri3** [comment]
`D1, D2` are SciMLOperators, `[D1, D2] isa Vector{<AbstractSciMLOperator}`, and `Diagonal([D1, D2]) isa Diagonal` matrix whose entries are SciMLOperators

**Comment by vpuri3** [comment]
I'm just doing matrix algebra to form my operators.

```julia
    TT = [T1, T2]
    DD = Diagonal([D1, D2])

    op = TT' * DD * TT
 ```

**Comment by gaurav-arya** [comment]
Hm, I see. Note that `DD` behaves a bit unintuitively, e.g. `size(DD) = (2,2)`

**Comment by gaurav-arya** [comment]
I'll need to modify the test to make all of these SciMLOperators because otherwise `update_coefficients!` isn't going to work. Although, it doesn't seem possible to make a lazy diagonal SciMLOperator currently?

**Comment by vpuri3** [comment]
No. All you need to do is pass an `update_func` to `T1, T2, D1, D2`. Leave the operator forming, matrix algebra as it is. When you call `update_coeffs!(op,...; kw...)` or `op(du, u, p, t; kw...)`, everything should just work

**Comment by gaurav-arya** [comment]
Right, my bad, on the same page now

**Comment by vpuri3** [comment]
excellent. :D can you close this if all is good?
