### ISSUE TITLE
`update_coefficients!` currently broken, probably needs mutable structs

### ISSUE THREAD

**Issue by danielwe** [SciML/SciMLOperators.jl#56]
For leaf nodes that aren't simple array wrappers, such as `ScalarOperator` and `FunctionOperator`, DiffEqOperators.jl had mutable structs that would be changed in-place by `update_coefficients!`. In contrast, SciMLOperators.jl seems to opt for immutable structs and use Setfield.jl. Example:

https://github.com/SciML/SciMLOperators.jl/blob/7dd3a9d89273039268b650f873e6ff10ec285a27/src/sciml.jl#L372-L376

However, this is incompatible with, for example, using a SciMLOperator as the `jac_prototype` in an in-place `ODEFunction`. Lines such as the following expect the operator to be updated in-place: https://github.com/SciML/OrdinaryDiffEq.jl/blob/3076b4ef7015cc3d683a82087761d56f20ac43d9/src/derivative_utils.jl#L148

Also, if you actually want to migrate to Setfield.jl despite this issue, the approach currently looks broken for recursive updating of composite operators. The following function will throw away any out-of-place Setfield-style changes and only keep in-place changes:

https://github.com/SciML/SciMLOperators.jl/blob/7dd3a9d89273039268b650f873e6ff10ec285a27/src/interface.jl#L22-L27

**Comment by vpuri3** [comment]
@danielwe , integrating SciMLOps with the rest of the ecosystem is a WIP. Ref https://github.com/SciML/SciMLOperators.jl/issues/55.

> Also, if you actually want to migrate to Setfield.jl despite this issue, the approach currently looks broken for recursive updating of composite operators. The following function will throw away any out-of-place Setfield-style changes and only keep in-place changes:
> 
> https://github.com/SciML/SciMLOperators.jl/blob/7dd3a9d89273039268b650f873e6ff10ec285a27/src/interface.jl#L22-L27

yeah that's on me. we copied that code from DiffEqOperators/SciMLBase/whatever and never bothered to fix the `update_coefficients` functionality to play nice with `@set!`. I'd be appreciative of any PRs that way since i can't get to that immediately, and not very familiar with the use cases.

@ChrisRackauckas is taking the lead on overhauling the ecosystem. He can comment on temp workarounds if any

**Comment by danielwe** [comment]
I had a brief slack discussion with @ChrisRackauckas back when I was trying to make LinearMaps work for my Jacobian. I had written functions to update the wrapped arrays, but couldn't update the scalar in a ScaledMap because ScaledMap is an immutable struct. Chris confirmed that if `f` is an in-place ODEFunction, the DifferentialEquations API requires actually mutating `J` inside `f.jac(J, u, p, t)`, and there's no plan or desire to change this to use the return value instead, or otherwise support hybrid ODEFunctions with in-place `f` and out-of-place `jac`. The solution I was presented with was to migrate from LinearMaps to DiffEqOperators precisely because they are mutable across the board. So unless that sentiment has changed and there's a plan to change the DifferentialEquations API, I really think SciMLOperators need to be mutable.

Though I'm curious which of the types actually need to be mutable structs to accomplish this. `ScalarOperator` and `FunctionOperator` are obvious because you need in-place updating of the scalar and `(u, p, t)`. `MatrixOperator` is less clear; it usually wraps a mutable array which is what you actually want to update, but I suppose it could also wrap a `StaticArray`, so in principle, it would have to be a mutable struct to make sure it always supports in-place updating, though that seems like a strange way to use it. I guess all the composition operators can remain immutable as long as updating only means updating data, not structure.

**Comment by vpuri3** [comment]
in-place updates are important so we don't go overboard in terms of memory in a long time-integration. at the same time mutable structs have a performance penalty that we need to avoid. @danielwe LMK if im trivializing the issue, but immutable structs aren't completely incompatible with in-place updates.

```julia
julia> using LinearAlgebra; struct A; a; end; a=A(zeros(4,4)); mul!(a.a, rand(4,4), rand(4,4)); a.a
4×4 Matrix{Float64}:
 0.211014  0.517916  0.747367  0.216454
 0.489373  0.949217  0.558255  0.842663
 0.319928  0.593095  0.574043  0.400424
 0.990797  1.53009   0.773686  1.50887
```

For `ScalarOperator`, we can always just dump the scalar in an array, and access it via `Base.first`. For `FunctionOperator` maybe we can wrap the parameters in `ComponentArrays` or some other structure that can be updated in place.

What I'm getting at is that "I" think we should be able to get away with immutability if it is important. LMK otherwise :))

**Comment by ChrisRackauckas** [comment]
```julia
 function update_coefficients!(L::FunctionOperator, u, p, t) 
     @set! L.p = p 
     @set! L.t = t 
     L 
 end 
```

yes that's just incorrect because that's not mutating. It should be able to do its operations and return `nothing` and still work. If we want to support a version without this mutation we could make a separate ConstantFunctionOperator, or have FunctionOperator default to `nothing,nothing` and then have an inner constructor where if parameters and time are given they are `Ref(p)`'d, so then this would be:

```julia
 function update_coefficients!(L::FunctionOperator, u, p, t) 
     L.p[] = p 
     L.t[] = t 
     nothing
 end 
```

We should also update all `update_coefficients!` implementations to `return nothing`.

**Comment by danielwe** [comment]
> immutable structs aren't completely incompatible with in-place updates

Absolutely, if the struct wraps something mutable you can just mutate that. The issue is with structs that wrap immutable stuff, such as `ScalarOperator` and `FunctionOperator`. (There's also the question of what to do when a `MatrixOperator` wraps a `StaticArray`, but that seems much less important in practice.)

> For `ScalarOperator`, we can always just dump the scalar in an array, and access it via `Base.first`.

> have an inner constructor where if parameters and time are given they are `Ref(p)`'d

When I've profiled this, a mutable struct always performs better than an immutable struct wrapping a `RefValue` or size-1 array (granted, with `RefValue` the difference is small, but it's reproducible).

> maybe we can wrap the parameters in `ComponentArrays` or some other structure that can be updated in place.

That's a huge constraint on what I can put in `p` that would only kick in for workflows that use this package. And again, a mutable struct performs better.

In general, I think it's important to keep in mind the context here. Unless I've misunderstood, this package is supposed to integrate fully with SciML workflows. In that case, mutability is simply required for compatibility with how the rest of the ecosystem is designed. (Of course, you're the ones designing and developing the package, I'm just a pestering user with high hopes for what I'll be able to do with it. Hope to find time to contribute PRs soon.)

**Comment by ChrisRackauckas** [comment]
We should just treat the constant operators as a special case. Mutation is more common in PDE areas because manual memory management is required for scaling anyways. The immutable are nice for cases where you want to build and destroy them all of the time, but these you want to build and update over a whole solve. That's mutation.

**Comment by vpuri3** [comment]
i might need non-mutating for working with Zygote. Not sure how AD would work for this package. We have defined `adjoint`s for most operators... I think except `AffineOperator` and `FunctionOperator`

**Comment by ChrisRackauckas** [comment]
That's a special case. Mutation is the norm for PDE solvers for a good reason. We should make these mutating and then have versions for constant if necessary.

The chains rules are mostly handled by using adjoint methods in the ODE solver anyways do the mutation is not even seen.

**Comment by vpuri3** [comment]
close?
